sudo: true
language: node_js
node_js:
- 6.13.0 # First to backport the WHATWG URL API
- 8
- 10
before_install:
- if [[ `npm --version` != 6* ]]; then npm install -g npm@6; fi && npm --version
script:
- npm run test:node
after_success:
- codecov -f coverage/*.json -F node
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
stages:
- lint
- test
- deploy

browser_defaults: &browser_defaults
  before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm run test-server:start:bg && sleep 2

jobs:
  include:
  - stage: lint
    script: npm run lint
  - stage: test
    <<: *browser_defaults
    addons:
      chrome: stable
    script: npm run test:browser -- --browsers ChromeHeadless
    after_success:
    - codecov -f coverage/headlesschrome/*.json -F browser
  - stage: test
    <<: *browser_defaults
    addons:
      firefox: latest
    script: npm run test:browser -- --browsers FirefoxHeadless
    after_success:
    - codecov -f coverage/firefox/*.json -F browser
  - stage: deploy
    node_js:
    - 8
    branches:
      only:
      - master
    script:
    - npm run deploy
env:
  global:
  - secure: bvBWZ4IjqkQdI6X+ETganN2zakWUPvWZxd5f8cIpZoetRXqCjWFecakD8TDcDa/nkPQ6Q3COdUnyZqZ8VkdWe6aE6xd2VX9U6HBDXzA/mTyD9f3Wj97opaWbpQa1FG7L2Ydq+gm2dDNhAqPO/503ePbbIJJ0rPOBbt8JF033ssvlzNlxVxG/1xAnC/PALEwsLON3z02+re6t6/uCPqdYg/QXRTnwNn6eplGaReJEGSaZXCBqSQN2jTc1tNh1Q9wo+MsyPwPvlF2Vo2wOeXEjLnI7fqjIAwAy70iwoBT72owIdJ1dd0CsOvGodtIDE8pL9indGZa/8kt4g/jjva4SXPBY0OI1gSQZTMBZCFFbj3MFMrrQSownX6kfPD49kmQbXsA/erjthM/lopYaBxkvtQxPzV5r8sid/AjWF3E371KxAClZhYNd2bs2SKNBEfhzuRXEuohpFcu95Pta6m8S1Z0rv61BTbhgNxooIq7EwC0LZSGX9eMT9O5SZHCRCX3mq10x86CM/xKz2WOEltj6Z3Ghg5qgb2AiJEMrS9vQPL3mAGN71eG/5vuiUsTCBPgOmSkh3w/S37mWeDrpe3Sl7IXNKjUB+guIxDNyoDzWX+4Vl2kAaQ2eC3ySz2tQvunb4K+FByG2do0zB8QTt1jA66AL7Ow62wWzlRsL25REpgA=
  - secure: xKJH9XU2jFHDUO+EPp9Lpg6qC5vzFTMpAWQT1NeQg66r88eiP7SVvDbDvDs4jovGZvS0dZXZwYWdFwCBYNG3WB360Qko1TMqCj8zslscp2j68hV3+3LXLK9tz7iUYoGmDy3/bz4fXoUn1Y91edyIvgAw/8orUZS2KU2EbC/YSHTMBAcsMX8ZJESRhJdVzxSChgGb1pIgp8WwFgi74fHoE0SJZwa28EoWpoJDmi7lgUzm0WRWPjPSvZU6AI4xZZ0lVbg2jvWztkRK7YhZhLNPHOF65LNvQHNIUAobBg5QS4rH70BCq2jGIsTP52YwW88AOs6KmuQlveF89vW9pyLLJ4nqILqANE8lCm38YmoX6zx66t0fImy5sD/MWaR8lxZK9j28KPQ133hUOsMHN9q3/4Bg8irvNlpR2ajro+oxqEONImlvd4Q88EC0nR1nbVpVbPLpwXdNzd2QJ9Ul9gCA+GuEfmP6tzP0HuvZ4tb5i+2f1IgRKrfQalqMmL2l/+BW5TIyo/HbnpCtb5yfVuPuNmwTu9MZroOUV2iIxQLyT1D81ml0fEb1UTCDeyR8sJICycRXayYnCkvdzd4d948RU/km0ZjBh3E6xryuQIzhSPLTzB7fcPPwzzq+h9YHWyxh9AEfNxdzm0J2oO9vDYBsKGN7mhYLZ7DLpjpJI2Uj6e0=
