sudo: true
language: node_js
node_js:
- 6.13.0
- 8
- 10
before_install:
- if [[ `npm --version` != 6* ]]; then npm install -g npm@6; fi && npm --version
script:
- npm run test:node
after_success:
- codecov -f coverage/*.json -F node
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
stages:
- lint
- test
- deploy
browser_defaults:
  before_script: &1
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run test-server:start:bg && sleep 2
ssh_deployment:
  before_script: &2
  - openssl aes-256-cbc -K $encrypted_ac56e3ed6a9b_key -iv $encrypted_ac56e3ed6a9b_iv
    -in git_deploy_key.enc -out /tmp/git_deploy_key -d
  - chmod 600 /tmp/git_deploy_key
  - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
  - eval "$(ssh-agent -s)"
  - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
jobs:
  include:
  - stage: lint
    script: npm run lint
  - stage: test
    before_script: *1
    addons:
      chrome: stable
    script: npm run test:browser -- --browsers ChromeHeadless
    after_success:
    - codecov -f coverage/headlesschrome/*.json -F browser
  - stage: test
    before_script: *1
    addons:
      firefox: latest
    script: npm run test:browser -- --browsers FirefoxHeadless
    after_success:
    - codecov -f coverage/firefox/*.json -F browser
  - stage: deploy
    before_script: *2
    node_js:
    - 8
    branches:
      only:
      - master
    script:
    - npm run deploy
env:
  global:
  - secure: dGumbdoQ3Fd561FqRD0Z+k3OIpjX+CsYNGSc5IVg87OsJR2BJnhj+HJcftL3xhA1grzlN5qdm4sGobaYhu40gNAvq+7ktEnwBmbVK/8mnRrYEC1+chymWsagK6Z1t1fxffKI+BV5cpGJFhdpLgLYS4RRsxOEopVj+4D8ErRchfUOY9jeW4gxhRDjYlajUv3Ok9xwXgah139cqmkVN5gRKgzX9Cbs1vFJ4Q1I4VoyeJUAB6y5qJu9wlrrNxJUVz40zSmSBD51cZS2rTb56cXp5eLca/31GE3qvuzwkFPkLmgYIJzdWNOsoXLRLja077JsJMNSOFhqkRGqLQaniA1VZks2jzMIpSJDb6jjdbHgiptD5XfUIxsFIXdYM1EqOvxDWLcONeFQcuK8VdaP6Zei1XlkQdJiDkFv37tqW2MOjsRNwa/dm/bgm15YHPRTSGm6MTDRKP0RafXRtdZrFKlD5VmCYodBXxu8sDIFAa8H2CzO3Al5HqydcSGVSL7+/LU5cldddG3nDOgaZQvihqzBz7sM+rdndrMy6Q25czYkfab0ULeXjYbTetFxJc5lcM91Nlrs82uhl3gdBTW666NCVqh8Ys3QPdI2PK8uZhPMnCYsRmpEM/Kjnzpgjr3EpuOT+zuah4ybTJxFDC6uXsO+mNy1N7vlDrHcVdDzN6vdVpQ=
  - secure: uwcyIwGG7M6Y9lKWA3n3C2+aHY2YpUFVFswPW4XM4s1IL2JGtriDix5JnW6vWDu3gPHi9KbrfKmKmuChsRlEodjs3NLJSergUArYTPimtJYdBbXYmnptmC991ikpS2tLlOOhF0tfBkuJDbfLL9th8599UfhtpG4rFx6slo0KwAJVgSr50o/msQtHj1QACFG5/Eck5oKvb8gB76LaIq4bES9r4ikoqNfCwTg20Pt5suytZzhb7xkftecTWgKQGg0QarfMICF3VOnkQAIwenKXhghmVOtXnSDj31/jO4xlcwPauxeJNrKhIHDGzYp1yocs3vj1kuj7uONGhKYf5M6tQtFsM8nM7EYuerDGeGW6xDy82wA5l0E0hcqoNqqvYhGAht+VemL84uhuvR8Lu6Eyj+c8Oq6fGgwSNEBN5FX4aP0gyEs7grsdn0BFDiwXktk70RKNnxtoPYrP/ZTKfTcyfs5UUOpq/NCGkWbbqrLnXLlQQ/D8e4Clxc61iHP/zPvW0pc8MZRVtPpIAFAnExDYDZEKGe8tAGV9EFhyn5Y1kmAOIxXPI8fNQ03/wijM3l4dOTK4jX+sSlhK0iYh6P84zpXbXgHVSA8lRDVS0niggVLdhDsVdwJrL5KN0GQwApcUlGLPNPeMO2THOMug1AsMccdhzetVyW+9WSKyJI8fp8A=
